version: '2'
services:
  ws-server:
    image: ws-server:latest
    network_mode: "bridge"
    ports:
      - "4010:4010"
    environment:
      - ENV=default
    command: /bin/ws-server
    volumes:
      - ./logs:/logs
      - ./configs:/configs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"